services:
  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./server
    ports:
      - "5000:5000"
    depends_on:
      - db
    env_file:
      - ./server/.env

  frontend:
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - backend
    env_file:
      - ./client/.env

volumes:
  mongo-data:
